Muchas cosas nuevas, falta por terminar el /scripts/bridge y su apartado en pagina web, tambien, fraccionar pagina web en archivos

diff --git a/scripts/bridge b/scripts/bridge
--- a/scripts/bridge
+++ b/scripts/bridge
@@ -1,5 +1,9 @@
 #!/bin/bash
 
+######################################################################
+###  Funcions
+######################################################################
+
 fnc_iniciar(){
     echo "iniciar"
     ##Falta estado bridge por iniciar si ya esta funcionando
@@ -20,13 +24,16 @@ fnc_iniciar(){
         VLAN_UNTAG=$(echo "$LINIA" | cut -d ';' -f2)
         VLAN_TAG=$(echo "$LINIA" | cut -d ';' -f3)
         ip l s dev $NOMBRE_IF master br0
+        bridge vlan del dev $NOM_IF vid 1 pvid untagged
+        #bridge vlan del dev $NOM_IF type vlan id $VLANID
         if [ ! -z $VLAN_UNTAG ]; then
-            bridge vlan add dev $VLAN_IF vid $VLAN_UNTAG pvid untagged
+            bridge vlan add dev $NOM_IF vid $VLAN_UNTAG pvid untagged
+            bridge vlan add dev br0 vid $VLAN_UNTAG self
         fi
-
         if [ ! -z $VLAN_TAG ]; then
             for CAMP in ${VLAN_TAG//,/ }; do 
-                bridge vlan add dev $VLAN_IF vid $VLAN_TAG
+                bridge vlan add dev $NOM_IF vid $CAMP
+                bridge vlan add dev br0 vid $CAMP self
             done
         fi
     done    
@@ -38,17 +45,146 @@ fnc_parar(){
 }
 
 fnc_configurar(){
-    echo "config"
+    if [ $# -lt 1 ]; then
+      echo "Falta [Mostrar, Guardar o Borrar]"
+      exit
+    fi
+
+    ARG_1=$1
+    shift
+
+    case "$ARG_1" in
+      mostrar)
+        if [ "$1" == "vlan" ]; then 
+          cat "/usr/local/JSBach/conf/bridge.conf" | grep -v '^#'
+        fi
+        if [ "$1" == "vlan" ]; then
+          cat "/usr/local/JSBach/conf/bridge_if.conf" | grep -v '^#'
+        fi
+      ;;
+      guardar) 
+        # --- Comprobación del tipo (vlan o bridge) ---
+        if [ -z "$1" ]; then
+          echo "Falta tipo [ Vlan/Bridge ]"
+          exit 1
+        fi
+        OPCIO_2=$1
+        shift 
+
+        case "$OPCIO_2" in
+          vlan)
+            # Espera: nombre ; VLANID ; IP/MASCARA ; IP_DISPOSITIVO
+            if [ -z "$1" ]; then
+              echo "Falta: [ Nombre ]"
+              exit 1
+            fi
+            if [ -z "$2" ]; then
+              echo "Falta: [ VLAN ID ]"
+              exit 1
+            fi
+            if [ -z "$3" ]; then
+              echo "Falta: [ IP/MASC ]"
+              exit 1
+            fi
+            if [ -z "$4" ]; then
+              echo "Falta [ IP/MASC Dev ]"
+              exit 1
+            fi
+
+            RESULTAT=$(grep -v ";$2;" "/usr/local/JSBach/conf/bridge.conf")
+            echo "$RESULTAT" > "/usr/local/JSBach/conf/bridge.conf"
+            echo "$1;$2;$3;$4;" >> "/usr/local/JSBach/conf/bridge.conf"
+          ;;
+          
+          #bridge no estoy seguro si esta bien, creo que esta mal.
+          bridge)
+            # Espera: nombre ; VLANID ; IP_DISPOSITIVO
+            if [ -z "$1" ]; then
+              echo "Falta: [ Nombre ]"
+              exit 1
+            fi
+            if [ -z "$2" ]; then
+              echo "Falta: [ VLAN ID ]"
+              exit 1
+            fi
+            if [ -z "$3" ]; then
+              echo "Falta [ IP/MASC Dev ]"
+              exit 1
+            fi
+
+            RESULTAT=$(grep -v ";$2;" "/usr/local/JSBach/scripts/bridge")
+            echo "$RESULTAT" > "/usr/local/JSBach/scripts/bridge"
+            echo "$1;$2;$3;" >> "/usr/local/JSBach/scripts/bridge"
+          ;;
+          
+          *)
+            echo "Error: tipo no válido. Usa [vlan o bridge]"
+            exit 1
+          ;;
+        esac	    
+      ;; 
+      #bridge no estoy seguro si esta bien, creo que esta mal.
+
+      borrar)
+        # --- Comprobación del tipo (vlan o bridge) ---
+        if [ -z "$1" ]; then
+          echo "Falta tipo: [ Vlan o Bridge ]"
+          exit 1
+        fi
+
+        if [ "$1" == "vlan" ]; then 
+          if [ -z "$2" ]; then
+            echo "Falta: [ VLAN ID ]"
+            exit 1
+          fi
+          if [ "$2" -lt 3 ]; then
+            echo "no se puede borrar la vlan $2"
+            if [ "$1" == "ok" ]; then 
+              echo " Estas seguro que quieres borrar esa Vlan?"
+              if [ "$1" == "ok" ]; then
+                echo "Funcion de borrado de vlans 1 o 2 aun (y no creo q nunca)
+                esta implementada porque mi programador es un poco tonto"
+                #Aqui deberia borrar las vlan pertinentes (1 o 2)
+                exit
+              fi
+            fi
+          fi
+          RESULTAT=$(grep -v ";$2;" "/usr/local/JSBach/conf/bridge.conf")
+          echo "VLANs: "
+          echo "$RESULTAT" > "/usr/local/JSBach/conf/bridge.conf"
+          echo "$RESULTAT"
+        elif [ "$1" == "bridge" ]; then
+          echo "Función de borrado de bridge aún no implementada pq mi programador es un poco tonto"
+        else
+          echo "Tipo no válido. Usa [vlan o bridge]"
+          exit 1
+        fi
+      ;;
+    esac
 }
+
 fnc_estado(){
-    echo "estado"
+  if ip -br a show dev br0 &>/dev/null; then
+	     echo "$ACTIVAT"
+	     echo "subinterfaces"
+	     for LINIA in $(cat "$DIR/$PROJECTE/$DIR_CONF/$BRIDGE_CONF" | grep -v '^#'); do
+	     	VLANID=$(echo "$LINIA"|cut -d';' -f2)
+	     	ip -4 -br a show dev br0.$VLANID
+	     done
+	     echo " " 
+	     echo "TAG, UNTAG"	     
+	     bridge vlan show
+	else
+	     echo "Desactivado"	
+	fi
 }
+
 
 ######################################################################
 ###  MAIN
 ######################################################################
 
-MSG="falta [iniciar, aturar, configurar ,estat]"
+MSG="Falta [Iniciar, Parar, Configurar o Estado]"
 
 # Comprovem que hi hagi almenys un argument (la opció)
 if [ $# -lt 1 ]; then
@@ -70,11 +206,10 @@ case "$OPCIO_1" in
   configurar) 
     fnc_configurar $@
     ;;
-  estat) 
-    fnc_estat $@
+  estado) 
+    fnc_estado $@
     ;;
   *)
     echo "$MSG"
     ;;
 esac
-
