Más o menos pero listo para entregar. Falta pulir tanto el cortafuegos, como el bridge como la toolbary una pagina principal con stats, pero bien, decente y bonito

diff --git a/scripts/cortafuegos b/scripts/cortafuegos
--- a/scripts/cortafuegos
+++ b/scripts/cortafuegos
@@ -1,124 +1,178 @@
 #!/bin/bash
 
-source /usr/local/JSBach/conf/variables.conf
-
 ######################################################################
 ###  Funcions
 ######################################################################
 
-fnc_iniciar()
-{
+# Comprobar root
+if [ "$(id -u)" -ne 0 ]; then
+	echo "Aquest script s'ha d'executar com a root"
+	exit 1
+fi
+
+fnc_iniciar(){
 	fnc_aturar
-	echo "Iniciar"	
-		
-	
-	for linia in $(grep -v '#' "$DIR/$PROJECTE/$DIR_CONF/$BRIDGE_CONF"); do
-	    nom=$(echo "$linia"|cut -d';' -f1)
-	    ip=$(echo "$linia"|cut -d';' -f3)
-	    iptables -N $nom
-	    iptables -A FORWARD -s $ip -j $nom	    
-	done
-	
+	echo "Iniciar"
+
+	# Crear cadenes per VLAN
+	while IFS= read -r linia; do
+	    [ -z "$linia" ] && continue
+
+	    nom=$(echo "$linia" | cut -d';' -f1)
+	    ip=$(echo "$linia"  | cut -d';' -f3)
+
+	    # Crear cadena només si no existeix
+	    iptables -L "$nom" -n >/dev/null 2>&1 || iptables -N "$nom"
+	    iptables -A FORWARD -s "$ip" -j "$nom"
+	done < <(grep -v '^#' /usr/local/JSBach/conf/bridge.conf)
+
+	# Cadena ports_wls
+	iptables -L ports_wls -n >/dev/null 2>&1 || iptables -N ports_wls
+
+	while IFS= read -r linia; do
+	    [ -z "$linia" ] && continue
+
+	    protocol=$(echo "$linia" | cut -d';' -f1)
+	    num_port=$(echo "$linia" | cut -d';' -f2)
+
+	    iptables -A ports_wls -p "$protocol" --dport "$num_port" -j ACCEPT
+	done < <(grep -v '^#' /usr/local/JSBach/conf/ports_wls.conf)
+
+	iptables -A ports_wls -j DROP
 }
 
-fnc_aturar()
-{
-	echo "Aturar"
+fnc_aturar(){
+	echo "Parando"
+
 	iptables -F
 	iptables -X
 	iptables -P FORWARD ACCEPT
 	iptables -P INPUT ACCEPT
 	iptables -P OUTPUT ACCEPT
-	
-	
-	resultat=$($DIR/$PROJECTE/$DIR_SCRIPTS/enrutar estat)
 
-	# Comprovem si conté la paraula "ACTIVAT"
-	echo "$resultat" | grep -q "$ACTIVAT"
+	resultat=$(/usr/local/JSBach/scripts/enrutar estado)
 
-	if [ $? -eq 0 ]; then
-		iptables -t nat -F 
+	if echo "$resultat" | grep -q "ACTIVAT"; then
+		iptables -t nat -F
 		iptables -t nat -X
-		$DIR/$PROJECTE/$DIR_SCRIPTS/enrutar iniciar
+		/usr/local/JSBach/scripts/enrutar iniciar
 	else
-		iptables -t nat -F 
+		iptables -t nat -F
 		iptables -t nat -X
-	fi	
+	fi
 }
 
+fnc_configurar(){
+	echo "Configuracion"
 
-fnc_configurar()
-{	
-	
-	echo "Configuracio"
-	
+	# Si no se pasa ninguna acción
+	if [ $# -lt 1 ]; then
+		echo "Falta [ conectar | desconectar | conectar_puertos_wls ]:"
+		exit 1
+	fi
+
 	ARG_1=$1
 	shift
-			
-	# Fem switch per executar la funció que toca
+
+	# Si no se pasa vlan
+	if [ $# -lt 1 ]; then
+		echo "Falta vlan"
+		exit 1
+	fi
+
 	case "$ARG_1" in
-	  desconnectar)
-	        linia=$(cat "$DIR/$PROJECTE/$DIR_CONF/$BRIDGE_CONF"| grep ";$1;" )
-	        nom=$( echo $linia | cut -d';' -f1)
+	  desconectar)
+	        linia=$(grep ";$1;" /usr/local/JSBach/conf/bridge.conf)
+	        nom=$(echo "$linia" | cut -d';' -f1)
+	        vid=$(echo "$linia" | cut -d';' -f2)
+
 	        if [ -z "$nom" ]; then
-		    echo "Error no existeix vlan $1"
-		else
-		    iptables -F $nom
-		    iptables -A $nom -j DROP
-		fi
+		    	echo "Error no existe la vlan $1"
+			else
+			    iptables -F "$nom"
+
+			    # IPs privilegiadas
+			 	while IFS= read -r ipwls; do
+				    ip=$(echo "$ipwls" | cut -d';' -f2)
+					mac=$(echo "$ipwls" | cut -d';' -f3)
+				    iptables -A "$nom" -s "$ip" -m mac --mac-source "$mac" -j ACCEPT
+				done < <(grep -v '^#' /usr/local/JSBach/conf/ip_wls.conf | grep "^$vid;")
+
+			    iptables -A "$nom" -j DROP
+			fi
 	  	;;
-	  connectar)
-	        linia=$(cat "$DIR/$PROJECTE/$DIR_CONF/$BRIDGE_CONF"| grep ";$1;" )
-	        nom=$( echo $linia | cut -d';' -f1)
+	  conectar)
+	        linia=$(grep ";$1;" /usr/local/JSBach/conf/bridge.conf)
+	        nom=$(echo "$linia" | cut -d';' -f1)
+
 	        if [ -z "$nom" ]; then
-		    	echo "Error no existeix vlan $1"
-		else
-			iptables -F $nom
-		fi	        
+		    	echo "ERROR, no existe la vlan $1"
+			else
+				iptables -F "$nom"
+			fi
+	  	;;
+	  conectar_puertos_wls)
+	        linia=$(grep ";$1;" /usr/local/JSBach/conf/bridge.conf)
+	        nom=$(echo "$linia" | cut -d';' -f1)
+	        vid=$(echo "$linia" | cut -d';' -f2)
+
+	        if [ -z "$nom" ]; then
+		    	echo "ERROR, no existe la vlan $1"
+			else
+				iptables -F "$nom"
+
+			 	while IFS= read -r ipwls; do
+				    ip=$(echo "$ipwls" | cut -d';' -f2)
+				    mac=$(echo "$ipwls" | cut -d';' -f3)
+				    iptables -A "$nom" -s "$ip" -m mac --mac-source "$mac" -j ACCEPT
+				done < <(grep -v '^#' /usr/local/JSBach/conf/ip_wls.conf | grep "^$vid;")
+
+				iptables -A "$nom" -j puertos_wls
+			fi
 	  	;;
 	  *)
-	        echo "Error  argumnets conectar, desconectar"
+	        echo "Error argumentos:"
+	        echo "  conectar <vlan>"
+	        echo "  desconectar <vlan>"
+	        echo "  conectar_puertos_wls <vlan>"
 	        ;;
-	esac	
-	
+	esac
 }
 
 
-fnc_estat()
-{	
+fnc_estat(){
+	echo "Puedes poner el nombre de la vlan"
 	if [ $# -eq 0 ]; then
-		 #echo "$ACTIVAT"
-		 #echo "$DESACTIVAT"
 		 echo MAIN
 		 iptables -nvL --line-numbers
 		 echo
-		 echo
-		 echo NAT	 
+		 echo NAT
 		 iptables -t nat -nvL --line-numbers
-		 exit 1
+		 echo "Puedes poner el nombre de la vlan"
+		 exit 0
 	fi
-	
-	        linia=$(cat "$DIR/$PROJECTE/$DIR_CONF/$BRIDGE_CONF"| grep ";$1;" )
-	        nom=$( echo $linia | cut -d';' -f1)
-	        if [ -z "$nom" ]; then
-		    echo "Error no existeix vlan $1"
-		else
-		     	if iptables -C $nom -j DROP 2>/dev/null; then
-			    echo "DESCONNECTADA"
-			else
-			    echo "CONNECTADA"
-			fi 
-		fi
-}
 
+
+	linia=$(grep ";$1;" /usr/local/JSBach/conf/bridge.conf)
+	nom=$(echo "$linia" | cut -d';' -f1)
+
+	if [ -z "$nom" ]; then
+		echo "ERROR, No existe la vlan $1"
+	else
+		if iptables -C "$nom" -j DROP 2>/dev/null; then
+			echo "DESCONNECTADA"
+		else
+			echo "CONNECTADA"
+		fi
+	fi
+}
 
 ######################################################################
 ###  MAIN
 ######################################################################
 
-MSG="falta [iniciar, aturar, configurar ,estat]"
+MSG="falta [iniciar, parar, configurar o estado]"
 
-# Comprovem que hi hagi almenys un argument (la opció)
 if [ $# -lt 1 ]; then
   echo "$MSG"
   exit 1
@@ -127,23 +181,20 @@ fi
 OPCIO_1=$1
 shift
 
-# Fem switch per executar la funció que toca
 case "$OPCIO_1" in
   iniciar)
-    fnc_iniciar  $@
+    fnc_iniciar "$@"
     ;;
-  aturar)
-    fnc_aturar	$@
-    ;; 
-  configurar) 
-    fnc_configurar $@
+  parar)
+    fnc_aturar "$@"
     ;;
-  estat) 
-    fnc_estat $@
+  configurar)
+    fnc_configurar "$@"
+    ;;
+  estado)
+    fnc_estat "$@"
     ;;
   *)
     echo "$MSG"
     ;;
 esac
-
-
